name: vms_employee_flutter
version: 0.0.5+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^9.2.0
  flutter_secure_storage: ^5.0.2
  get: 4.6.1
  google_fonts: ^2.2.0
  intl: ^0.17.0
  pie_chart: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/vms_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
